import { Work } from './types';

export const mockWorks: Work[] = [
  {
    id: 1,
    title: 'Курсовая работа по экономике',
    description: 'Готовая курсовая работа на тему "Анализ финансового состояния предприятия"',
    price: 2500,
    originalPrice: 3000,
    discount: 17,
    category: 'Курсовые работы',
    subject: 'Экономика',
    workType: 'Курсовая работа',
    rating: 4.8,
    reviewsCount: 12,
    viewsCount: 156,
    purchasesCount: 8,
    author: {
      id: 1,
      name: 'Иван Петров',
      rating: 4.9,
    },
    files: [
      { id: 1, name: 'kursovaya.docx', type: 'docx', size: 245000, url: '#' },
      { id: 2, name: 'presentation.pptx', type: 'pptx', size: 1200000, url: '#' },
    ],
    tags: ['экономика', 'финансы', 'анализ'],
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2024-12-10T15:30:00Z',
    isFavorite: false,
  },
  {
    id: 2,
    title: 'Реферат по истории России',
    description: 'Реферат на тему "Великая Отечественная война 1941-1945"',
    price: 800,
    category: 'Рефераты',
    subject: 'История',
    workType: 'Реферат',
    rating: 4.5,
    reviewsCount: 5,
    viewsCount: 89,
    purchasesCount: 3,
    author: {
      id: 2,
      name: 'Мария Сидорова',
      rating: 4.7,
    },
    files: [
      { id: 3, name: 'referat.pdf', type: 'pdf', size: 180000, url: '#' },
    ],
    tags: ['история', 'война', 'россия'],
    createdAt: '2024-11-25T14:20:00Z',
    updatedAt: '2024-12-08T09:15:00Z',
    isFavorite: true,
  },
  {
    id: 3,
    title: 'Лабораторная работа по физике',
    description: 'Лабораторная работа "Изучение законов механики"',
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    category: 'Лабораторные работы',
    subject: 'Физика',
    workType: 'Лабораторная работа',
    rating: 5.0,
    reviewsCount: 8,
    viewsCount: 124,
    purchasesCount: 6,
    author: {
      id: 3,
      name: 'Алексей Смирнов',
      rating: 5.0,
    },
    files: [
      { id: 4, name: 'lab_work.docx', type: 'docx', size: 156000, url: '#' },
      { id: 5, name: 'calculations.xlsx', type: 'xlsx', size: 89000, url: '#' },
    ],
    tags: ['физика', 'механика', 'лабораторная'],
    createdAt: '2024-12-05T11:45:00Z',
    updatedAt: '2024-12-11T16:20:00Z',
    isFavorite: false,
  },
];

export const mockCategories = [
  'Все категории',
  'Курсовые работы',
  'Дипломные работы',
  'Рефераты',
  'Контрольные работы',
  'Лабораторные работы',
  'Эссе',
  'Отчеты по практике',
];

export const mockSubjects = [
  'Все предметы',
  'Математика',
  'Физика',
  'Химия',
  'Биология',
  'История',
  'Литература',
  'Экономика',
  'Программирование',
];
