# Generated by Django 5.2.1 on 2026-03-11 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('room_type', models.CharField(choices=[('general', 'Общий'), ('department', 'Отдел'), ('project', 'Проект'), ('private', 'Приватный')], default='general', max_length=20, verbose_name='Тип комнаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_partner_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('members', models.ManyToManyField(related_name='partner_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Чат-комната партнеров',
                'verbose_name_plural': 'Чат-комнаты партнеров',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системное сообщение')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='partners.partnerchatroom', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Сообщение в чате партнеров',
                'verbose_name_plural': 'Сообщения в чатах партнеров',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partnerchatroom',
            index=models.Index(fields=['is_active', '-updated_at'], name='partners_pa_is_acti_a77cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerchatroom',
            index=models.Index(fields=['room_type', '-updated_at'], name='partners_pa_room_ty_c6bd56_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerchatmessage',
            index=models.Index(fields=['room', 'created_at'], name='partners_pa_room_id_fc927f_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerchatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='partners_pa_sender__801558_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerchatmessage',
            index=models.Index(fields=['is_pinned', '-created_at'], name='partners_pa_is_pinn_6f3826_idx'),
        ),
    ]
