# Generated by Django 5.2.1 on 2026-07-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerapplication'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerapplication',
            new_name='partners_pa_status_b2b577_idx',
            old_name='partners_pa_status_idx',
        ),
    ]
