# Generated by Django 5.2.16 on 2026-08-03 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_rename_partners_pa_status_idx_partners_pa_status_b2b577_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerchatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='partner_chat_files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='partnerchatmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла'),
        ),
        migrations.CreateModel(
            name='RoomReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего прочтения')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='partners.partnerchatroom', verbose_name='Комната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_room_read_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус прочтения',
                'verbose_name_plural': 'Статусы прочтения',
                'db_table': 'partner_chat_read_statuses',
                'unique_together': {('user', 'room')},
            },
        ),
    ]
