# Generated by Django 5.2.1 on 2025-11-11 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_subject_options"),
        ("orders", "0009_bid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["expert", "status", "-created_at"],
                name="orders_orde_expert__a21fbb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "subject", "-created_at"],
                name="orders_orde_status_89dad3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at"], name="orders_orde_created_f0ce29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "-timestamp"], name="orders_tran_user_id_b8e561_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "type", "-timestamp"],
                name="orders_tran_user_id_515605_idx",
            ),
        ),
    ]
