# Generated by Django 5.2.1 on 2025-12-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_orders_orde_expert__a21fbb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Произвольный предмет'),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_work_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Произвольный тип работы'),
        ),
    ]
