# Generated by Django 5.2.1 on 2026-01-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_custom_subject_order_custom_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('active', 'Активная'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
