# Generated by Django 5.2.1 on 2026-02-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_issues',
            field=models.BooleanField(default=False, help_text='Отметка о наличии проблем с заказом', verbose_name='Есть проблемы'),
        ),
    ]
