# Generated by Django 5.2.1 on 2026-03-13 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_freeze_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='prepayment_percent',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент предоплаты'),
        ),
    ]
