# Generated by Django 5.2.1 on 2026-03-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_bid_prepayment_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Бюджет'),
        ),
    ]
