# Generated by Django 5.2.1 on 2026-03-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_note',
            field=models.TextField(blank=True, help_text='Приватная заметка заказчика, видимая только ему', null=True, verbose_name='Заметка клиента'),
        ),
    ]
