# Generated by Django 5.2.1 on 2026-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_status_maxlen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('active', 'Активная'), ('invited', 'Ожидает ответа эксперта'), ('accepted', 'Принята экспертом'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
