# Generated by Django 5.2.16 on 2026-07-26 13:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Бюджет'),
        ),
    ]
