# Generated by Django 5.2.16 on 2026-07-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_order_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('hold', 'Заморозка'), ('release', 'Разморозка'), ('payout', 'Выплата'), ('commission', 'Комиссия'), ('refund', 'Возврат'), ('topup', 'Пополнение'), ('withdrawal', 'Вывод средств'), ('purchase', 'Покупка'), ('partner_payout', 'Выплата партнеру')], max_length=20),
        ),
    ]
