# Generated by Django 5.2.16 on 2026-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_add_partner_payout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_type',
            field=models.CharField(
                choices=[('fixed', 'Фиксированная цена'), ('negotiable', 'Договорная цена')],
                default='fixed',
                max_length=16,
                verbose_name='Тип цены',
            ),
        ),
    ]
