# Generated by Django 5.2.16 on 2026-08-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ready_work_purchase',
            field=models.BooleanField(default=False, help_text='Заказ создан автоматически из покупки в магазине готовых работ', verbose_name='Это покупка готовой работы'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_deadline',
            field=models.DateTimeField(blank=True, help_text='Крайний срок, до которого продавец/система должна передать готовую работу покупателю', null=True, verbose_name='Дедлайн передачи готовой работы'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_started_at',
            field=models.DateTimeField(blank=True, help_text="Когда заказ перешёл в статус 'Передача готовой работы' (старт таймера)", null=True, verbose_name='Момент начала передачи готовой работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('awaiting_expert_acceptance', 'Ожидает ответа эксперта'), ('waiting_payment', 'Ожидает оплаты'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('revision', 'На доработке'), ('completed', 'Выполнен'), ('cancelled', 'Отменен'), ('expired', 'Истёк срок'), ('ready_work_transfer', 'Передача готовой работы')], default='new', max_length=32, verbose_name='Статус'),
        ),
    ]
