# Generated by Django 5.2.16 on 2026-08-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_transfer_deadline_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='auto_bad_review_issued',
            field=models.BooleanField(default=False, help_text='Выставляется, когда клиент отменил заказ после истечения таймера передачи', verbose_name='Авто-отзыв 1★ уже выставлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transfer_deadline_notified_at',
            field=models.DateTimeField(blank=True, help_text='Чтобы не дублировать уведомление эксперту от периодической задачи', null=True, verbose_name='Когда эксперту ушло уведомление «таймер истёк, клиент может отменить»'),
        ),
    ]
