# Generated by Django 5.2.16 on 2026-08-08 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='prepayment_percent',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(100)], verbose_name='Процент предоплаты'),
        ),
    ]
