# Generated by Django 5.2.16 on 2026-08-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_bid_prepayment_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('hold', 'Заморозка'), ('release', 'Разморозка'), ('payout', 'Выплата'), ('commission', 'Комиссия'), ('refund', 'Возврат'), ('topup', 'Пополнение'), ('withdrawal', 'Вывод средств'), ('purchase', 'Покупка'), ('partner_payout', 'Выплата партнеру'), ('clawback', 'Списание по возврату')], max_length=20),
        ),
    ]
