export const API_ENDPOINTS = {
  auth: {
    login: '/users/token/',
    register: '/users/',
    me: '/users/me/',
    refreshToken: '/users/token/refresh/',
    verifyEmailCode: '/users/verify_email_code/',
    resendVerificationCode: '/users/resend_verification_code/',
    requestPasswordReset: '/users/request_password_reset/',
    telegramAuth: '/users/telegram_auth/', 
    telegramAuthStatus: (authId: string) => `/users/telegram_auth_status/${authId}/`,
    googleLogin: '/accounts/google/login/?process=login',
    vkLogin: '/accounts/vk/login/',
    resetPasswordWithCode: '/users/reset_password_with_code/',
    resetPasswordConfirm: '/users/reset_password_confirm/',
  },
  users: {
    recent: '/users/recent_users/',
    publicStats: '/public/stats/',
    supportUser: '/users/support_user/',
    updateProfile: '/users/update_me/',
    submitExpertApplication: '/users/submit_expert_application/',
  },
  orders: {
    list: '/orders/orders/',
    available: '/orders/orders/available/',
    clientOrders: '/users/client_orders/',
    detail: (id: number) => `/orders/orders/${id}/`,
    take: (id: number) => `/orders/orders/${id}/take/`,
    complete: (id: number) => `/orders/orders/${id}/complete/`,
    submit: (id: number) => `/orders/orders/${id}/submit/`,
    approve: (id: number) => `/orders/orders/${id}/approve/`,
    revision: (id: number) => `/orders/orders/${id}/revision/`,
    extendDeadline: (id: number) => `/orders/orders/${id}/extend_deadline/`,
    cancelOverdue: (id: number) => `/orders/orders/${id}/cancel_overdue/`,
    uploadFile: (id: number) => `/orders/orders/${id}/files/`,
    bids: (id: number) => `/orders/orders/${id}/bids/`,
    acceptBid: (id: number) => `/orders/orders/${id}/accept_bid/`,
    rejectBid: (id: number) => `/orders/orders/${id}/reject_bid/`,
    cancelBid: (id: number) => `/orders/orders/${id}/cancel_bid/`,
    comments: (id: number) => `/orders/orders/${id}/comments/`,
    downloadFile: (id: number, fileId: number) => `/orders/orders/${id}/files/${fileId}/download/`,
  },
  admin: {
    users: {
      list: '/admin-panel/users/',
      blocked: '/admin-panel/users/blocked/',
      block: (id: number) => `/admin-panel/users/${id}/block/`,
      unblock: (id: number) => `/admin-panel/users/${id}/unblock/`,
      changeRole: (id: number) => `/admin-panel/users/${id}/change_role/`,
      arbitrators: '/users/admin_arbitrators/',
    },
    roles: {
      list: '/admin-panel/roles/',
      detail: (id: string) => `/admin-panel/roles/${id}/`,
      permissions: '/admin-panel/permissions/',
      updatePermissions: (id: string) => `/admin-panel/roles/${id}/permissions/`,
    },
    finance: {
      tariffs: {
        list: '/admin-panel/tariffs/',
        detail: (id: number) => `/admin-panel/tariffs/${id}/`,
      },
      commissions: {
        list: '/admin-panel/commissions/',
        detail: (id: number) => `/admin-panel/commissions/${id}/`,
      },
      partners: '/users/admin_partners/',
      earnings: '/users/admin_earnings/',
      updatePartner: (id: number) => `/users/${id}/admin_update_partner/`,
      markEarningPaid: '/users/admin_mark_earning_paid/',
    },
    orders: {
      list: '/admin-panel/orders/',
      problems: '/admin-panel/orders/problems/',
      changeStatus: (id: number) => `/admin-panel/orders/${id}/change-status/`,
    },
    content: {
      stats: '/admin-panel/stats/',
      works: {
        list: '/admin-panel/works/',
        approve: (id: number) => `/admin-panel/works/${id}/approve/`,
        reject: (id: number) => `/admin-panel/works/${id}/reject/`,
      },
    },
    communication: {
      chatRooms: {
        list: '/admin-panel/chat-rooms/',
        detail: (id: number) => `/admin-panel/chat-rooms/${id}/`,
        messages: (id: number) => `/admin-panel/chat-rooms/${id}/messages/`,
        join: (id: number) => `/admin-panel/chat-rooms/${id}/join/`,
        leave: (id: number) => `/admin-panel/chat-rooms/${id}/leave/`,
        invite: (id: number) => `/admin-panel/chat-rooms/${id}/invite/`,
        files: (id: number) => `/admin-panel/chat-rooms/${id}/files/`,
      },
      director: {
        list: '/admin-panel/director-communications/',
        messages: (id: number) => `/admin-panel/director-communications/${id}/messages/`,
        sendMessage: (id: number) => `/admin-panel/director-communications/${id}/send_message/`,
      },
    },
    support: {
      requests: {
        list: '/admin-panel/support-requests/',
        detail: (id: number) => `/admin-panel/support-requests/${id}/`,
        assign: (id: number) => `/admin-panel/support-requests/${id}/assign/`,
        take: (id: number) => `/admin-panel/support-requests/${id}/take/`,
        complete: (id: number) => `/admin-panel/support-requests/${id}/complete/`,
        messages: (id: number) => `/admin-panel/support-requests/${id}/messages/`,
      },
      claims: {
        list: '/admin-panel/claims/',
        detail: (id: number) => `/admin-panel/claims/${id}/`,
        assign: (id: number) => `/admin-panel/claims/${id}/assign/`,
        take: (id: number) => `/admin-panel/claims/${id}/take/`,
        complete: (id: number) => `/admin-panel/claims/${id}/complete/`,
        reject: (id: number) => `/admin-panel/claims/${id}/reject/`,
        progress: (id: number) => `/admin-panel/claims/${id}/progress/`,
        reopen: (id: number) => `/admin-panel/claims/${id}/reopen/`,
        approve: (id: number) => `/admin-panel/claims/${id}/approve/`,
        rejectApproval: (id: number) => `/admin-panel/claims/${id}/reject-approval/`,
        escalate: (id: number) => `/admin-panel/claims/${id}/escalate/`,
        requestInfo: (id: number) => `/admin-panel/claims/${id}/request-info/`,
        messages: (id: number) => `/admin-panel/claims/${id}/messages/`,
      },
      chats: {
        list: '/admin-panel/support-chats/',
        messages: (id: number) => `/admin-panel/support-chats/${id}/messages/`,
      },
    },
  },
  support: {
    chats: '/chat/support/',
    messages: (chatId: number) => `/chat/support/${chatId}/messages/`,
    sendMessage: (chatId: number) => `/chat/support/${chatId}/send_message/`,
    take: (chatId: number) => `/chat/support/${chatId}/take_chat/`,
    close: (chatId: number) => `/chat/support/${chatId}/close_chat/`,
    createTicket: (chatId: number) => `/chat/support/${chatId}/create_ticket/`,
  },
  partners: {
    dashboard: '/users/partner_dashboard/',
    generateLink: '/users/generate_referral_link/',
  },
} as const;
