import dayjs from 'dayjs';

// Тестовые данные заказов для ленты работ
export const MOCK_ORDERS = [
  {
    id: 1001,
    title: 'Курсовая работа по высшей математике',
    description: 'Необходимо выполнить курсовую работу по теме "Дифференциальные уравнения второго порядка". Объем 25-30 страниц, требуется решение 10 задач с подробными пояснениями.',
    budget: 3500,
    deadline: dayjs().add(5, 'days').toISOString(),
    status: 'open',
    subject_name: 'Математика',
    work_type_name: 'Курсовая работа',
    subject_id: 1,
    work_type_id: 2,
    created_at: dayjs().subtract(2, 'hours').toISOString(),
    responses_count: 3,
    client_name: 'Анна К.',
    client_avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 5
  },
  {
    id: 1002,
    title: 'Реферат по истории России',
    description: 'Тема: "Внешняя политика России в XIX веке". Объем 15-20 страниц, список литературы не менее 10 источников.',
    budget: 1500,
    deadline: dayjs().add(3, 'days').toISOString(),
    status: 'open',
    subject_name: 'История',
    work_type_name: 'Реферат',
    subject_id: 5,
    work_type_id: 1,
    created_at: dayjs().subtract(5, 'hours').toISOString(),
    responses_count: 7,
    client_name: 'Дмитрий П.',
    client_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 12
  },
  {
    id: 1003,
    title: 'Лабораторная работа по физике',
    description: 'Выполнить лабораторную работу по теме "Изучение законов постоянного тока". Нужны расчеты, графики и выводы.',
    budget: 2000,
    deadline: dayjs().add(2, 'days').toISOString(),
    status: 'open',
    subject_name: 'Физика',
    work_type_name: 'Лабораторная работа',
    subject_id: 2,
    work_type_id: 3,
    created_at: dayjs().subtract(1, 'day').toISOString(),
    responses_count: 12,
    client_name: 'Елена С.',
    client_avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 3
  },
  {
    id: 1004,
    title: 'Дипломная работа по программированию',
    description: 'Разработка веб-приложения для управления задачами на React + Node.js. Требуется полная документация, исходный код и презентация.',
    budget: 25000,
    deadline: dayjs().add(30, 'days').toISOString(),
    status: 'open',
    subject_name: 'Информатика',
    work_type_name: 'Дипломная работа',
    subject_id: 3,
    work_type_id: 5,
    created_at: dayjs().subtract(3, 'days').toISOString(),
    responses_count: 5,
    client_name: 'Максим В.',
    client_avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 1
  },
  {
    id: 1005,
    title: 'Контрольная работа по английскому языку',
    description: 'Выполнить 5 заданий: перевод текста, грамматические упражнения, эссе на тему "My Future Career".',
    budget: 800,
    deadline: dayjs().add(1, 'day').toISOString(),
    status: 'open',
    subject_name: 'Английский язык',
    work_type_name: 'Контрольная работа',
    subject_id: 6,
    work_type_id: 4,
    created_at: dayjs().subtract(6, 'hours').toISOString(),
    responses_count: 15,
    client_name: 'Ольга М.',
    client_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 8
  },
  {
    id: 1006,
    title: 'Решение задач по химии',
    description: 'Нужно решить 20 задач по органической химии с подробными объяснениями механизмов реакций.',
    budget: 1200,
    deadline: dayjs().add(4, 'days').toISOString(),
    status: 'open',
    subject_name: 'Химия',
    work_type_name: 'Решение задач',
    subject_id: 4,
    work_type_id: 6,
    created_at: dayjs().subtract(8, 'hours').toISOString(),
    responses_count: 8,
    client_name: 'Игорь Л.',
    client_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 4
  },
  {
    id: 1007,
    title: 'Эссе по философии',
    description: 'Написать эссе на тему "Проблема свободы воли в современной философии". Объем 5-7 страниц.',
    budget: 1000,
    deadline: dayjs().add(7, 'days').toISOString(),
    status: 'open',
    subject_name: 'Философия',
    work_type_name: 'Эссе',
    subject_id: 7,
    work_type_id: 7,
    created_at: dayjs().subtract(12, 'hours').toISOString(),
    responses_count: 4,
    client_name: 'Мария Н.',
    client_avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 2
  },
  {
    id: 1008,
    title: 'Презентация по маркетингу',
    description: 'Создать презентацию на тему "Цифровой маркетинг в 2024 году". 15-20 слайдов с инфографикой.',
    budget: 2500,
    deadline: dayjs().add(6, 'days').toISOString(),
    status: 'open',
    subject_name: 'Маркетинг',
    work_type_name: 'Презентация',
    subject_id: 8,
    work_type_id: 8,
    created_at: dayjs().subtract(4, 'hours').toISOString(),
    responses_count: 6,
    client_name: 'Сергей Б.',
    client_avatar: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 15
  },
  {
    id: 1009,
    title: 'Курсовая по экономике предприятия',
    description: 'Анализ финансового состояния предприятия. Нужны расчеты показателей, таблицы, графики и рекомендации.',
    budget: 4000,
    deadline: dayjs().add(10, 'days').toISOString(),
    status: 'open',
    subject_name: 'Экономика',
    work_type_name: 'Курсовая работа',
    subject_id: 9,
    work_type_id: 2,
    created_at: dayjs().subtract(1, 'day').toISOString(),
    responses_count: 9,
    client_name: 'Татьяна Р.',
    client_avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 7
  },
  {
    id: 1010,
    title: 'Отчет по практике',
    description: 'Написать отчет по производственной практике в IT-компании. Объем 30-35 страниц.',
    budget: 3000,
    deadline: dayjs().add(8, 'days').toISOString(),
    status: 'open',
    subject_name: 'Информатика',
    work_type_name: 'Отчет',
    subject_id: 3,
    work_type_id: 9,
    created_at: dayjs().subtract(2, 'days').toISOString(),
    responses_count: 2,
    client_name: 'Алексей Ж.',
    client_avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face',
    client_orders_count: 1
  }
];
