# Generated by Django 5.2.16 on 2026-08-23 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0004_settlement_funded_base_settlement_funded_service_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('inn', models.CharField(db_index=True, max_length=12, verbose_name='ИНН')),
                ('tax_status', models.CharField(choices=[('self_employed', 'Самозанятый (НПД)'), ('entrepreneur', 'Индивидуальный предприниматель'), ('individual', 'Физическое лицо')], default='self_employed', max_length=20, verbose_name='Налоговый статус')),
                ('status', models.CharField(choices=[('not_submitted', 'Не подана'), ('pending', 'На проверке'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=16, verbose_name='Статус проверки')),
                ('npd_confirmed', models.BooleanField(blank=True, help_text='null — проверить не удалось', null=True, verbose_name='Подтверждён как плательщик НПД')),
                ('npd_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки в ФНС')),
                ('npd_message', models.TextField(blank=True, default='', verbose_name='Ответ ФНС')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Верификация личности',
                'verbose_name_plural': 'Верификации личности',
                'db_table': 'verification_identity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NpdStatusCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Момент проверки')),
                ('is_self_employed', models.BooleanField(blank=True, help_text='null — ФНС недоступна', null=True, verbose_name='Плательщик НПД')),
                ('message', models.TextField(blank=True, default='', verbose_name='Ответ ФНС')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Сырой ответ')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npd_checks', to='verification.identityverification', verbose_name='Верификация')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npd_checks', to='wallet.withdrawalrequest', verbose_name='Заявка на вывод')),
            ],
            options={
                'verbose_name': 'Проверка статуса НПД',
                'verbose_name_plural': 'Проверки статуса НПД',
                'db_table': 'verification_npd_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['status', '-created_at'], name='verificatio_status_530cb5_idx'),
        ),
    ]
