# Generated by Django 5.2.1 on 2026-04-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0002_add_complaint_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='arbitrationcase',
            new_name='arbitration_status_228f1c_idx',
            old_name='arbitration_status_idx',
        ),
        migrations.RenameIndex(
            model_name='arbitrationcase',
            new_name='arbitration_plainti_6033db_idx',
            old_name='arbitration_plaintiff_idx',
        ),
        migrations.RenameIndex(
            model_name='arbitrationcase',
            new_name='arbitration_defenda_91c63e_idx',
            old_name='arbitration_defendant_idx',
        ),
        migrations.RenameIndex(
            model_name='arbitrationcase',
            new_name='arbitration_assigne_133fd7_idx',
            old_name='arbitration_admin_status_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='arbitration_status_26bc23_idx',
            old_name='arb_complaint_status_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='arbitration_order_i_45dbb2_idx',
            old_name='arb_complaint_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='arbitration_plainti_6bebab_idx',
            old_name='arb_complaint_plaintiff_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='arbitration_defenda_aaf6fa_idx',
            old_name='arb_complaint_defendant_idx',
        ),
    ]
