# Generated by Django 5.2.16 on 2026-08-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0003_rename_arbitration_status_idx_arbitration_status_228f1c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitrationcase',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('under_review', 'На рассмотрении'), ('awaiting_response', 'Ожидает ответа'), ('in_arbitration', 'В арбитраже'), ('pending_approval', 'Ожидает согласования возврата'), ('decision_made', 'Решение принято'), ('closed', 'Закрыто'), ('rejected', 'Отклонено')], default='draft', max_length=30, verbose_name='Статус'),
        ),
    ]
