# Generated by Django 5.2.1 on 2026-08-08 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0004_add_pending_approval_status'),
        ('shop', '0010_alter_purchase_hold_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrationcase',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitration_cases', to='shop.purchase', verbose_name='Связанная покупка'),
        ),
        migrations.AlterField(
            model_name='arbitrationcase',
            name='reason',
            field=models.CharField(choices=[('order_not_completed', 'Заказ не выполнен'), ('poor_quality', 'Низкое качество работы'), ('deadline_violation', 'Нарушение сроков'), ('payment_dispute', 'Спор по оплате'), ('contract_violation', 'Нарушение условий договора'), ('ready_work_dispute', 'Спор по готовой работе'), ('other', 'Другое')], max_length=50, verbose_name='Причина обращения'),
        ),
    ]
