# Generated by Django 5.2.1 on 2026-04-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_article_articlefile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='knowledge_a_created_76c3d8_idx',
            old_name='knowledge_a_created_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='knowledge_a_work_ty_e8d5ee_idx',
            old_name='knowledge_a_work_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='knowledge_a_subject_249d46_idx',
            old_name='knowledge_a_subject_idx',
        ),
    ]
