# Generated by Django 5.2.16 on 2026-08-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_articlecomplaint_articledeletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='Содержание ответа'),
        ),
    ]
