# Generated by Django 5.2.1 on 2026-01-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_bid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('sbp', 'Система быстрых платежей'), ('card', 'Банковская карта')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'Обрабатывается'), ('completed', 'Оплачен'), ('failed', 'Ошибка'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_id', models.CharField(max_length=255, unique=True, verbose_name='ID платежа в платежной системе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('metadata', models.JSONField(default=dict, verbose_name='Дополнительные данные')),
                ('encrypted_data', models.TextField(blank=True, null=True, verbose_name='Зашифрованные данные')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
