# Generated by Django 5.2.1 on 2026-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_topup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('sbp', 'Система быстрых платежей'), ('card', 'Банковская карта')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
