# Generated by Django 5.2.16 on 2026-07-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_method_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('sbp', 'Система быстрых платежей'), ('card', 'Банковская карта'), ('sberbank', 'Sberbank'), ('sberpay_qr', 'SberPay QR')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
