# Generated by Django 5.2.1 on 2025-11-01 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_franchisee_user_active_referrals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_approved',
            field=models.BooleanField(default=False, verbose_name='Анкета одобрена'),
        ),
        migrations.AddField(
            model_name='user',
            name='application_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки по анкете'),
        ),
        migrations.AddField(
            model_name='user',
            name='application_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения анкеты'),
        ),
        migrations.AddField(
            model_name='user',
            name='application_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Кто рассмотрел анкету'),
        ),
        migrations.AddField(
            model_name='user',
            name='application_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи анкеты'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_submitted_application',
            field=models.BooleanField(default=False, verbose_name='Анкета подана'),
        ),
    ]
