# Generated by Django 5.2.1 on 2025-11-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_application_approved_user_application_notes_and_more'),
        ('users', '0007_user_email_verified_emailverificationcode'),
    ]

    operations = [
    ]
