# Generated by Django 5.2.1 on 2026-02-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20260221_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('expert', 'Expert'), ('admin', 'Admin'), ('director', 'Director'), ('partner', 'Partner')], default='client', max_length=20),
        ),
    ]
