# Generated by Django 5.2.1 on 2026-03-30 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_username_validator'),
        ('users', '0015_alter_user_username'),
    ]

    operations = [
    ]
