# Generated by Django 5.2.1 on 2026-04-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_blocking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_ban_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действителен до (временный бан)'),
        ),
    ]
