# Generated by Django 5.2.1 on 2026-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_friendship_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='VK ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='VK уведомления включены'),
        ),
    ]
