# Generated by Django 5.2.16 on 2026-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0024_alter_user_options_user_user_balance_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма невыплаченных партнерских начислений', max_digits=12, verbose_name='Ожидает выплаты'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('pending_balance__gte', 0)), name='user_pending_balance_non_negative'),
        ),
    ]
