# Generated by Django 5.2.16 on 2026-08-08 20:46

from django.db import migrations, models

def set_partner_defaults(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='partner').update(partner_commission_rate=25)
    for user in User.objects.filter(partner__isnull=False, partner_linked_at__isnull=True).iterator():
        user.partner_linked_at = user.date_joined
        user.save(update_fields=['partner_linked_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_compute_pending_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner_linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки к партнеру'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_commission_rate',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Процент партнера (%)'),
        ),
        migrations.RunPython(set_partner_defaults, migrations.RunPython.noop),
    ]
