# Generated by Django 5.2.16 on 2026-08-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_partner_linked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerearning',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Источник начисления'),
        ),
    ]
