# Generated by Django 5.2.16 on 2026-08-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0028_partnerearning_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debt_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задолженность по возвратам'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('debt_balance__gte', 0)), name='user_debt_balance_non_negative'),
        ),
    ]
