# Generated by Django 5.2.16 on 2026-09-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_debt_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — общий процент площадки. 0 — без комиссии.', max_digits=5, null=True, verbose_name='Индивидуальный сервисный сбор (%)'),
        ),
    ]
