# Generated by Django 5.2.16 on 2026-09-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_user_service_fee_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdrawal_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — общий процент по роли. 0 — без удержания.', max_digits=5, null=True, verbose_name='Индивидуальное удержание при выводе (%)'),
        ),
    ]
