# Generated by Django 5.2.16 on 2026-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_withdrawal_fee_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_payments_allowed',
            field=models.BooleanField(default=False, help_text='Только для тестовых аккаунтов: оплата не списывает реальных денег.', verbose_name='Может платить через тестовый магазин'),
        ),
    ]
