import { PurchasedWork } from './types';

export const mockPurchasedWorks: PurchasedWork[] = [
  {
    id: 1,
    title: 'Курсовая работа по программированию',
    type: 'Курсовая работа',
    subject: 'Информатика',
    price: 2500,
    originalPrice: 3000,
    purchaseDate: '2024-01-15T10:30:00',
    downloadUrl: '/downloads/work-1.pdf',
    isDownloaded: true,
    downloadCount: 3,
    description: 'Разработка веб-приложения на React',
    rating: 5,
    reviewsCount: 12,
  },
  {
    id: 2,
    title: 'Лабораторная работа по физике',
    type: 'Лабораторная работа',
    subject: 'Физика',
    price: 800,
    purchaseDate: '2024-01-20T14:15:00',
    downloadUrl: '/downloads/work-2.pdf',
    isDownloaded: false,
    downloadCount: 0,
    description: 'Изучение законов механики',
    rating: 4.8,
    reviewsCount: 8,
  },
  {
    id: 3,
    title: 'Реферат по истории России',
    type: 'Реферат',
    subject: 'История',
    price: 600,
    originalPrice: 750,
    purchaseDate: '2024-02-01T09:00:00',
    downloadUrl: '/downloads/work-3.pdf',
    isDownloaded: true,
    downloadCount: 1,
    description: 'Эпоха Петра I',
    rating: 4.5,
    reviewsCount: 5,
  },
];
