# Generated by Django 5.2.1 on 2025-11-02 09:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0007_remove_expertstatistics_orders_cancelled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "work_experience_years",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Опыт работы (лет)",
                    ),
                ),
                (
                    "specializations",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Укажите специальности, которые вы пишете (можно через запятую или каждую на новой строке)",
                        verbose_name="Специальности",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В рассмотрении"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Причина отклонения"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата рассмотрения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "expert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_application",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Эксперт",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_expert_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто рассмотрел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анкета эксперта",
                "verbose_name_plural": "Анкеты экспертов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=255, verbose_name="ВУЗ")),
                (
                    "start_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Год начала обучения",
                    ),
                ),
                (
                    "end_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Год окончания обучения",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Степень/Квалификация"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создан"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="experts.expertapplication",
                        verbose_name="Анкета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образования",
                "ordering": ["-end_year", "-start_year"],
            },
        ),
    ]
