# Generated by Django 5.2.1 on 2025-11-11 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0008_expertapplication_education"),
        ("orders", "0009_bid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expertreview",
            index=models.Index(
                fields=["expert", "is_published", "-created_at"],
                name="experts_exp_expert__ca8094_idx",
            ),
        ),
    ]
