# Generated by Django 5.2.1 on 2025-12-13 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_subject_options"),
        ("experts", "0009_expertreview_experts_exp_expert__ca8094_idx"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="specialization",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="expertapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В рассмотрении"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                    ("deactivated", "Деактивировано"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experts",
                to="catalog.subject",
                verbose_name="Предмет",
            ),
        ),
    ]
