# Generated by Django 5.2.1 on 2026-02-20 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0012_specialization_skills"),
        ("orders", "0013_order_has_issues"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expertrating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="expertstatistics",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0, verbose_name="Всего отзывов"),
        ),
        migrations.AddIndex(
            model_name="expertrating",
            index=models.Index(
                fields=["expert", "-created_at"], name="experts_exp_expert__ebb851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expertrating",
            index=models.Index(
                fields=["client", "-created_at"], name="experts_exp_client__7d6181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expertrating",
            index=models.Index(fields=["rating"], name="experts_exp_rating_2ca8c7_idx"),
        ),
    ]
