# Generated by Django 5.2.1 on 2026-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0014_change_specializations_to_manytomany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertapplication',
            name='specializations_old',
            field=models.TextField(blank=True, default='', help_text='Старое текстовое поле', null=True, verbose_name='Специальности (старое)'),
        ),
    ]
