# Generated by Django 5.2.1 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0015_alter_expertapplication_specializations_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertapplication',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'В рассмотрении'),
                    ('approved', 'Одобрено'),
                    ('rejected', 'Отклонено'),
                    ('needs_revision', 'На доработке'),
                    ('deactivated', 'Деактивировано'),
                ],
                default='pending',
                max_length=20,
                verbose_name='Статус',
            ),
        ),
    ]
