# Generated by Django 5.2.1 on 2026-01-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readywork",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="ready_works/previews/",
                verbose_name="Превью работы",
            ),
        ),
    ]
