# Generated by Django 5.2.1 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_readywork_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="delivered_file",
            field=models.FileField(blank=True, null=True, upload_to="purchases/", verbose_name="Файл работы"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="delivered_file_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Имя файла"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="delivered_file_size",
            field=models.PositiveIntegerField(default=0, verbose_name="Размер файла"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="delivered_file_type",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Тип файла"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="rated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата оценки"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Оценка"),
        ),
    ]

