# Generated by Django 5.2.1 on 2026-07-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_readywork_execution_days_purchase_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
    ]
