# Generated by Django 5.2.16 on 2026-07-13 21:26

from django.db import migrations, models


def backfill_moderation_status(apps, schema_editor):
    ReadyWork = apps.get_model('shop', 'ReadyWork')
    ReadyWork.objects.filter(is_active=True).update(moderation_status='approved')
    ReadyWork.objects.filter(is_active=False).update(moderation_status='rejected')


def restore_is_active_from_status(apps, schema_editor):
    ReadyWork = apps.get_model('shop', 'ReadyWork')
    ReadyWork.objects.filter(moderation_status='approved').update(is_active=True)
    ReadyWork.objects.exclude(moderation_status='approved').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_purchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='readywork',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_moderation_status, restore_is_active_from_status),
        migrations.AlterField(
            model_name='readywork',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
    ]
