# Generated by Django 5.2.1 on 2026-08-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_purchase_hold_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readywork',
            name='execution_days',
        ),
    ]
