# Generated by Django 5.2.16 on 2026-08-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_execution_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivered_file_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='readyworkfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип файла'),
        ),
    ]
