# Generated by Django 5.2.1 on 2026-02-10 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('message_type', models.CharField(choices=[('question', 'Вопрос'), ('report', 'Отчёт'), ('request', 'Запрос'), ('notification', 'Уведомление')], default='question', max_length=20, verbose_name='Тип сообщения')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='director.internalmessage', verbose_name='Родительское сообщение')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_internal_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_internal_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Внутреннее сообщение',
                'verbose_name_plural': 'Внутренние сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема встречи')),
                ('description', models.TextField(verbose_name='Описание')),
                ('proposed_date', models.DateTimeField(verbose_name='Предложенная дата')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Утверждённая дата')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Запрос на встречу',
                'verbose_name_plural': 'Запросы на встречи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='internal_messages/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='director.internalmessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='director_in_recipie_be2cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['sender', '-created_at'], name='director_in_sender__9bd85f_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['is_archived', '-created_at'], name='director_in_is_arch_34a650_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrequest',
            index=models.Index(fields=['status', '-created_at'], name='director_me_status_d50581_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrequest',
            index=models.Index(fields=['requester', '-created_at'], name='director_me_request_1acd54_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrequest',
            index=models.Index(fields=['director', 'status'], name='director_me_directo_92b02d_idx'),
        ),
    ]
