# Generated by Django 5.2.1 on 2026-03-04 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('room_type', models.CharField(
                    choices=[('general', 'Общий'), ('department', 'Отдел'), ('project', 'Проект'), ('private', 'Приватный')],
                    default='general',
                    max_length=20,
                    verbose_name='Тип комнаты'
                )),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_director_chat_rooms',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Создатель'
                )),
                ('members', models.ManyToManyField(
                    related_name='director_chat_rooms',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Участники'
                )),
            ],
            options={
                'verbose_name': 'Чат директора',
                'verbose_name_plural': 'Чаты директора',
                'db_table': 'director_chat_rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectorChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системное сообщение')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('room', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='messages',
                    to='director.directorchatroom',
                    verbose_name='Комната'
                )),
                ('sender', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Отправитель'
                )),
            ],
            options={
                'verbose_name': 'Сообщение в чате директора',
                'verbose_name_plural': 'Сообщения в чатах директора',
                'db_table': 'director_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='directorchatroom',
            index=models.Index(fields=['is_active', '-updated_at'], name='director_ch_is_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='directorchatroom',
            index=models.Index(fields=['room_type', '-created_at'], name='director_ch_room_ty_idx'),
        ),
        migrations.AddIndex(
            model_name='directorchatmessage',
            index=models.Index(fields=['room', 'created_at'], name='director_ch_room_id_idx'),
        ),
        migrations.AddIndex(
            model_name='directorchatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='director_ch_sender__idx'),
        ),
        migrations.AddIndex(
            model_name='directorchatmessage',
            index=models.Index(fields=['is_pinned', '-created_at'], name='director_ch_is_pinn_idx'),
        ),
    ]
