# Generated by Django 5.2.1 on 2026-02-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internalmessage',
            new_name='director_in_created_259d49_idx',
            old_name='director_in_created_idx',
        ),
        migrations.RenameIndex(
            model_name='internalmessage',
            new_name='director_in_sender__79542a_idx',
            old_name='director_in_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='internalmessage',
            new_name='director_in_recipie_ff06b8_idx',
            old_name='director_in_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='internalmessage',
            new_name='director_in_is_read_2a5fe5_idx',
            old_name='director_in_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='internalmessage',
            new_name='director_in_claim_i_0cd792_idx',
            old_name='director_in_claim_i_idx',
        ),
    ]
