# Generated by Django 5.2.1 on 2026-03-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_add_director_chat_rooms'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='directorchatmessage',
            new_name='director_ch_room_id_cc13f3_idx',
            old_name='director_ch_room_id_idx',
        ),
        migrations.RenameIndex(
            model_name='directorchatmessage',
            new_name='director_ch_sender__805469_idx',
            old_name='director_ch_sender__idx',
        ),
        migrations.RenameIndex(
            model_name='directorchatmessage',
            new_name='director_ch_is_pinn_e79c0e_idx',
            old_name='director_ch_is_pinn_idx',
        ),
        migrations.RenameIndex(
            model_name='directorchatroom',
            new_name='director_ch_is_acti_3bdc1b_idx',
            old_name='director_ch_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='directorchatroom',
            new_name='director_ch_room_ty_e11809_idx',
            old_name='director_ch_room_ty_idx',
        ),
    ]
