# Generated by Django 5.2.1 on 2026-03-23 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_rename_director_ch_room_id_idx_director_ch_room_id_cc13f3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('category', models.CharField(choices=[('expert_payments', 'Выплаты экспертам'), ('partner_payments', 'Партнерские выплаты'), ('marketing', 'Маркетинг'), ('infrastructure', 'Инфраструктура'), ('salaries', 'Зарплаты'), ('other', 'Прочее')], default='other', max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Ручной расход',
                'verbose_name_plural': 'Ручные расходы',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', '-created_at'], name='director_ma_date_aa9426_idx'), models.Index(fields=['category', '-date'], name='director_ma_categor_222b4a_idx'), models.Index(fields=['created_by', '-date'], name='director_ma_created_0d134a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManualIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('source', models.CharField(default='manual', max_length=100, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Ручной доход',
                'verbose_name_plural': 'Ручные доходы',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', '-created_at'], name='director_ma_date_263da2_idx'), models.Index(fields=['created_by', '-date'], name='director_ma_created_20bc7f_idx')],
            },
        ),
    ]
