# Generated by Django 5.2.1 on 2026-03-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_manualexpense_manualincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='manualincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма'),
        ),
    ]
