# Generated by Django 5.2.16 on 2026-08-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0006_remove_system_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorchatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='director_chat_files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='directorchatmessage',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='directorchatmessage',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
    ]
