# Generated by Django 5.2.1 on 2026-07-10 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0022_alter_bid_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('card_number', models.CharField(max_length=32, verbose_name='Карта (маскированная)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выплаты'), ('paid', 'Выплачено'), ('rejected', 'Отклонено')], default='pending', max_length=16, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='orders.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вывод',
                'verbose_name_plural': 'Заявки на вывод',
                'db_table': 'wallet_withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
