# Generated by Django 5.2.16 on 2026-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='acquiring_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Комиссия эквайринга'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Списано с кошелька'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Комиссия платформы'),
        ),
    ]
