# Generated by Django 5.2.16 on 2026-08-09 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_transaction_type'),
        ('shop', '0012_alter_purchase_delivered_file_type_and_more'),
        ('wallet', '0002_withdrawalrequest_acquiring_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refunded_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_settlements', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_settlements', to=settings.AUTH_USER_MODEL)),
                ('fee_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_settlements', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_settlement', to='orders.order')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_settlement', to='shop.purchase')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('purchase__isnull', True)), models.Q(('order__isnull', True), ('purchase__isnull', False)), _connector='OR'), name='settlement_exactly_one_source')],
            },
        ),
    ]
