# Generated by Django 5.2.16 on 2026-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='funded_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='settlement',
            name='funded_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='settlement',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
