# Generated by Django 5.2.16 on 2026-09-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_settlement_funded_base_settlement_funded_service_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='release_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
