# Generated by Django 5.2.1 on 2026-03-04 13:55

import apps.admin_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_add_ticket_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='ticket_number',
            field=models.CharField(default=apps.admin_panel.models.generate_ticket_number, max_length=16, unique=True, verbose_name='Номер тикета'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='ticket_number',
            field=models.CharField(default=apps.admin_panel.models.generate_ticket_number, max_length=16, unique=True, verbose_name='Номер тикета'),
        ),
    ]
