# Generated by Django 5.2.1 on 2026-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_add_arbitration_fields_to_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %'),
        ),
    ]
