# Generated by Django 5.2.1 on 2026-02-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('offer', 'Индивидуальное предложение')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
        migrations.AddField(
            model_name='message',
            name='offer_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные предложения'),
        ),
    ]
