# Generated by Django 5.2.1 on 2026-02-10 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_message_type_message_offer_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('resolved', 'Решен'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_support_chats', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chats', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Чат поддержки',
                'verbose_name_plural': 'Чаты поддержки',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('system', 'Системное')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('file', models.FileField(blank=True, null=True, upload_to='support_files/', verbose_name='Файл')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='chat.supportchat', verbose_name='Чат')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение поддержки',
                'verbose_name_plural': 'Сообщения поддержки',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['status', '-updated_at'], name='chat_suppor_status_d9161b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['client', '-created_at'], name='chat_suppor_client__fd156f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['admin', 'status'], name='chat_suppor_admin_i_58928f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['chat', 'created_at'], name='chat_suppor_chat_id_91e75c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['sender', '-created_at'], name='chat_suppor_sender__15fb95_idx'),
        ),
    ]
