# Generated by Django 5.2.1 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_message_type_message_offer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='context_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]

