# Generated by Django 5.2.1 on 2026-02-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_context_title'),
        ('chat', '0008_supportchat_supportmessage_and_more'),
    ]

    operations = [
    ]
