# Generated by Django 5.2.1 on 2026-02-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_merge_20260218_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('offer', 'Индивидуальное предложение'), ('work_offer', 'Предложение готовой работы'), ('work_delivery', 'Отправка готовой работы')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
    ]
