# Generated by Django 5.2.1 on 2026-02-22 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_merge_20260221_0001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactviolationlog',
            index=models.Index(fields=['user', '-detected_at'], name='chat_contac_user_id_f5486d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactviolationlog',
            index=models.Index(fields=['chat', '-detected_at'], name='chat_contac_chat_id_96dfea_idx'),
        ),
    ]
