# Generated by Django 5.2.1 on 2026-03-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_add_chat_moderation_fields'),
    ]

    operations = [
    ]
