# Generated by Django 5.2.1 on 2026-03-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20260303_2229'),
    ]

    operations = [
    ]
