# Generated by Django 5.2.1 on 2026-03-04 11:40

from django.db import migrations
from django.utils import timezone


def set_default_created_at(apps, schema_editor):
    """Устанавливает значение по умолчанию для created_at в существующих записях"""
    ContactViolationLog = apps.get_model('chat', 'ContactViolationLog')
    ContactViolationLog.objects.filter(created_at__isnull=True).update(
        created_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_add_system_message_type'),
    ]

    operations = [
        migrations.RunPython(set_default_created_at, migrations.RunPython.noop),
    ]
