# Generated by Django 5.2.1 on 2026-03-04 13:55

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_add_system_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactviolationlog',
            name='chat_contac_user_id_f5486d_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactviolationlog',
            name='chat_contac_chat_id_96dfea_idx',
        ),
        migrations.RenameIndex(
            model_name='contactviolationlog',
            new_name='chat_contac_status_afadca_idx',
            old_name='chat_contac_status_f8a9c1_idx',
        ),
        migrations.RenameIndex(
            model_name='contactviolationlog',
            new_name='chat_contac_risk_le_d04342_idx',
            old_name='chat_contac_risk_le_8b2d4f_idx',
        ),
        migrations.AlterField(
            model_name='contactviolationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='contactviolationlog',
            index=models.Index(fields=['user', '-created_at'], name='chat_contac_user_id_8c8148_idx'),
        ),
        migrations.AddIndex(
            model_name='contactviolationlog',
            index=models.Index(fields=['chat', '-created_at'], name='chat_contac_chat_id_3a12d0_idx'),
        ),
    ]
