# Generated by Django 5.2.1 on 2026-03-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20260304_1440'),
        ('chat', '0017_remove_contactviolationlog_chat_contac_user_id_f5486d_idx_and_more'),
    ]

    operations = [
    ]
