# Generated by Django 5.2.1 on 2026-03-13 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_merge_20260311_1336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='hidden_for_users',
            field=models.ManyToManyField(blank=True, related_name='hidden_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
