# Generated by Django 5.2.1 on 2026-03-13 18:10

from django.db import migrations, models


def deduplicate_direct_chats(apps, schema_editor):
    Chat = apps.get_model('chat', 'Chat')
    seen_pairs = {}
    ids_to_delete = []

    for row in Chat.objects.filter(
        order__isnull=True,
        client_id__isnull=False,
        expert_id__isnull=False
    ).values('id', 'client_id', 'expert_id').order_by('id'):
        pair = tuple(sorted((row['client_id'], row['expert_id'])))
        existing_id = seen_pairs.get(pair)
        if existing_id is None:
            seen_pairs[pair] = row['id']
            continue
        ids_to_delete.append(row['id'])

    if ids_to_delete:
        Chat.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('chat', '0019_chat_hidden_for_users'),
    ]

    operations = [
        migrations.RunPython(deduplicate_direct_chats, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(
                models.functions.Least('client_id', 'expert_id'),
                models.functions.Greatest('client_id', 'expert_id'),
                condition=models.Q(order__isnull=True, client__isnull=False, expert__isnull=False),
                name='unique_direct_chat_pair',
            ),
        ),
    ]
