# Generated by Django 5.2.1 on 2026-03-30 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_unique_direct_chat_pair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата закрепления')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='chat.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Закреплённый чат',
                'verbose_name_plural': 'Закреплённые чаты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='chat_chatpi_user_id_a66b38_idx')],
                'unique_together': {('user', 'chat')},
            },
        ),
    ]
